"""
This script will:
- copy scriptunzip.py + key_score.py + tasks.json from `fpsetup/` to the main course folder
- add the 'score' keybinding to VScode's keybindings.json
First script version generated by claude.ai Sonnet 4.6 Extended 2026-03-14

This is not yet very well tested - feedback is especially welcome!
See also:  https://code.visualstudio.com/docs/configure/keybindings

For this to work, open the main course folder in VScode, not fpsetup/ or an individual exercise subfolder.
"""

score_binding = {"key": "ctrl+shift+y",   # <-- change Keybinding here if wanted
                 "command": "workbench.action.tasks.runTask", 
                 "args": "score"}
# Note: in tasks.json, set "clear": false to see previous scoring runs in the dedicated terminal
                 
import os
import sys
import shutil
import platform
import json

# --- Check folder ---

# os.chdir("C:/Dropbox/HPI/FundamentalsProgramming") # for REPL
if not os.path.isdir("fpsetup"):
    print("Please run this script from the main course folder containing fpsetup/.")
    sys.exit(1)
print("NOTE: this is the main course folder:", os.getcwd())

# --- Copy scriptunzip.py, key_score.py and tasks.json to the main course folder ---

os.makedirs(".vscode", exist_ok=True)
shutil.copy2("fpsetup/scriptunzip.py", "scriptunzip.py")
shutil.copy2("fpsetup/key_score.py", "key_score.py")
shutil.copy2("fpsetup/tasks.json", ".vscode/tasks.json")

print("NOTE: exercise files were copied successfully :)")
 
# --- find VScode's keybindings.json ---
 
system = platform.system()
if system == "Windows":
    kb_path = os.path.join(os.environ.get("APPDATA", ""), "Code", "User", "keybindings.json")
elif system == "Darwin":
    kb_path = os.path.expanduser("~/Library/Application Support/Code/User/keybindings.json")
elif system == "Linux":
    kb_path = os.path.expanduser("~/.config/Code/User/keybindings.json")
else:
    print(f"Unrecognised OS: {system}. Cannot locate keybindings.json automatically.")
    sys.exit(1)

os.makedirs(os.path.dirname(kb_path), exist_ok=True)
if not os.path.exists(kb_path):
    open(kb_path, "w").close()
    print("NOTE: keybindings.json is newly created.")
print("NOTE: this is the Keybindings file:", kb_path)
 
# --- Read existing keybindings ---

with open(kb_path, encoding="utf-8") as f:
    kb_content = "\n".join(l for l in f if not l.lstrip().startswith("//")).strip()
if kb_content:
    try:
        bindings = json.loads(kb_content)
    except json.JSONDecodeError as e:
        print(f"Could not parse {kb_path}:\n  {e}")
        print("Please fix the file manually and re-run this script.")
        sys.exit(1)
else: 
    bindings = []

# --- Add keybinding ---
 
bindings.append(score_binding)
with open(kb_path, "w", encoding="utf-8") as f:
    json.dump(bindings, f, indent=4)
print("NOTE: Keybinding added successfully. Reload VScode (CTRL+SHIFT+P > 'Reload Window').")
